### ISSUE TITLE
Router

### ISSUE THREAD

**Issue by ArmchairGuy** [dracoapi/dracowalker#13]
Is there any way to change the 'human' router order of preference for the target such as - chests, stops, creatures, so that chests are prioritised?

**Comment by niicojs** [comment]
I think it's currently chest, creatures, stops
It make more sense to me, why do you think stop would be before creature?

**Comment by ArmchairGuy** [comment]
In the router.js there is a line:
return _.orderBy([stop, creature, chest].filter(o=>o), 'distance', 'asc')[0];

Or am I misreading it?

**Comment by niicojs** [comment]
I didn't remember I did that.
It actually take the closest one, without weight

**Comment by niicojs** [comment]
chest is now prioritized in human router
