### ISSUE TITLE
stops are registering as chests in debug log

### ISSUE THREAD

**Issue by sirlygo** [dracoapi/dracowalker#14]
20:30:21 - debug: Use stop 646d49bd-b504-11e7-a034-7fd1663ca285
20:30:21 - debug: Chest loot:
20:30:21 - debug:   1 Small Healing Potion.
20:30:21 - debug:   1 Small Healing Potion.
20:30:21 - debug:   1 Small Healing Potion.
20:30:21 - debug:   75 exp.

**Comment by niicojs** [comment]
thanks, fixed
