### ISSUE TITLE
API request quota exceeded?  

### ISSUE THREAD

**Issue by mitviet1** [dracoapi/dracowalker#16]
Just wonder if the error below indicates this is something a user running the bot would need to do or is it just because too many people using the same API in this repository.   
"   Error: You have exceeded your daily request quota for this API. We recommend registering for a key at the Google Developers Console: https://console.developers.google.com/apis/credentials?project=_
    at StopRouter.generateWaypoint (C:\Users\Tony Dao\dracowalker\bin\lib\router\BaseRouter.js:27:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) "

**Comment by niicojs** [comment]
It's because you need to create a google key to use google directions, in order to walk aonly on roads.  
See doc here: https://github.com/dracoapi/dracowalker/wiki/Google-Maps  

You can also disable it through:
```
behavior:
  followroads: false
```

**Comment by mitviet1** [comment]
Thanks. I created and activated the API key but somehow when I put the
command line: key=API_KEY in the config.yaml file then it always give me
syntax err when starting the bot.  I am not very familiar w/ this so not
sure if I am doing it correctly here or not.   Also all day today I can't
restarted the bot as each time I got this error messages below when
starting the bot w/ this command:   node ./bin/app.js  .  So wonder if you
know what the issue is.   Thanks again.

20:53:38 - info: App starting...
20:53:38 - info: go to http://ui.dracoapi.ml/ for ui
20:53:38 - debug: Socket server listening at 8000
20:53:38 - debug: Ping server...
20:53:39 - error:  Error: Error from server: 409 - Conflict
    at Client.call
(C:\Users\StarTraveller\dracowalker\node_modules\draconode\bin\index.js:141:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
20:53:39 - error: Exiting.

**Comment by niicojs** [comment]
It's:  
```
gmapKey: abcdef_XYZWG
```

**Comment by mitviet1** [comment]
Thanks so much.  I Still can't start the bot due to the error below.   Is
that something from the code/server itself?

C:\Users\......\dracowalker>node ./bin/app.js
08:54:43 - info: App starting...
08:54:43 - info: go to http://ui.dracoapi.ml/ for ui
08:54:43 - debug: Socket server listening at 8000
08:54:43 - debug: Ping server...
08:54:43 - *error:  Error: Error from server: 409 - Conflict*
    at Client.call
(C:\Users\......\dracowalker\node_modules\draconode\bin\index.js:141:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
08:54:43 - error: Exiting.

**Comment by niicojs** [comment]
Try to update everything
