### ISSUE TITLE
am i banned?

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#20]
Hey i got following error on login to the game

Error from server: 412 - Precondition Failed

**Comment by niicojs** [comment]
would it be possible to send me credentials?

**Comment by Nackenschelle** [comment]
ok i tested the login on my mobile phone
here is a proof of the ban: http://prntscr.com/hx89ke

**Comment by niicojs** [comment]
ok.
for the record, could you tell me what was the config and how long did you use it? (like 24h a day for a week?)

**Comment by Nackenschelle** [comment]
here are my settings

pos:
  lat: 40.782865
  lng: -73.965355

behavior:
  catch: true
  autorelease: true
  evolveperfect: true
  autoalliance: blue

router:
  name: human
  followroads: true
  prioritizechest: true

proxy: 
  url:

i used the bot 2 hours every day

**Comment by mitviet1** [comment]
just curious what lvl of your account when it was blocked/banned.   I am running the bot for 2 accts and they are still going 'ok' @ lvl 27 and 25.  I do run them mostly thru the night and sometimes many hours during the day.  And I stopped them at least once a day to log back on phone to collect coins/ take a gym/manually clean out item inventories, etc.   Then they are back to bot.  My settings are similar except my Followroads is False and don't have Autoalliance.
