### ISSUE TITLE
ui item use?

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#21]
hey sir is there any chance to add a function to use items by the ui?
dont want to login into bluestacks everytime for Dragon's Eyesight
thanks in advance

**Comment by xandymp** [comment]
It would be nice to have a way to know if there any buff active like pheromones or Dragon's Eyesight or even some buff that was given by a chest.

**Comment by niicojs** [comment]
you can now use incense or vision if you use latest dev version.

**Comment by xandymp** [comment]
What is the latest dev version?
I tried the 1.0.50 but didn't find how to use the items.

**Comment by niicojs** [comment]
in the ui, just over a incense or a vision thing-y and you should see a button to use it

**Comment by xandymp** [comment]
I dunno if I'm using the right version but as I said i'm using the version 1.0.50 from the dev build.
Couldn't see any button to use the item.
![00_2](https://user-images.githubusercontent.com/19960976/36725064-e088603e-1b93-11e8-83f2-f9a33e9d1300.jpg)

**Comment by niicojs** [comment]
ok, there was an issue with my automatic deployment
should be fixed

**Comment by xandymp** [comment]
Thanks! the icon showed up now and it is working like a charm

**Comment by xandymp** [comment]
Could you enable the crystal of wisdow too?

**Comment by niicojs** [comment]
I'll look into it

**Comment by niicojs** [comment]
done, if you can test

**Comment by xandymp** [comment]
When I tried to use it through the ui it showed the message
`info: Super vision already in use.`

**Comment by niicojs** [comment]
There is a bug which led to this message (corrected in `dev-1.0.62`), but I guess the underlying issue remains. Let me know when you'll test dev version >= 62.

**Comment by xandymp** [comment]
In version 1.0.64 when trying to use the crystal I got this message
`info: Unhandled item use: undefined`

**Comment by xandymp** [comment]
Tried again later and it looks like the crystal was used but there was no message on debug
