### ISSUE TITLE
can't connect - Error from server: 409 - Conflict

### ISSUE THREAD

**Issue by mitviet1** [dracoapi/dracowalker#23]
last couples days I've been having connect issue even after full updates.  Now each time, these are the messages and the bot just terminated.  
09:31:24 - info: App starting...
09:31:24 - info: go to http://ui.dracoapi.ml/ for ui
09:31:24 - debug: Socket server listening at 8000
09:31:24 - debug: Init walker...
09:31:24 - debug: Ping server...
09:31:25 - error:  Error: Error from server: 409 - Conflict
    at Client.call (C:\Users\......\dracowalker\node_modules\draconode\bin\index.js:141:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
09:31:25 - error: Exiting.

**Comment by niicojs** [comment]
A new app version has been release but I'm away from a computer all week

**Comment by Nackenschelle** [comment]
any eta?
iam lvl 39 and soon 40 :(

**Comment by niicojs** [comment]
https://github.com/dracoapi/dracowalker/releases/tag/1.0.5

**Comment by Nackenschelle** [comment]
works fine without problems thx mate

**Comment by mitviet1** [comment]
Thanks man. It works fine but found 1 weird thing.  I am running 2 accts
simultaneously but one 1 window, keep having the Warning msg below.  The
other appears to be just fine. Just FYI.

08:25:10 - warn: Unhandled object in map update: FQuestUpdate
08:25:21 - debug: Map Refresh lat=-43.52935279506227, lng=172.6335616882865
08:25:21 - warn: Unhandled object in map update: FQuestUpdate
08:25:31 - debug: Map Refresh lat=-43.52915469480707, lng=172.63357274126233
08:25:31 - warn: Unhandled object in map update: FQuestUpdate

**Comment by niicojs** [comment]
could you open another issue?
