### ISSUE TITLE
Warning: Unhandled object in map update: FQuestUpdate

### ISSUE THREAD

**Issue by mitviet1** [dracoapi/dracowalker#24]
I am running 2 separate Command windows for 2 accts.  On one of them, there is a warning msg keeps popping up but the other window is just fine.   Not impact anything but kind of weird that it happen on one acct but not the other.  I am using similar coords for both.

13:20:17 - debug: Map Refresh lat=-43.52265718865315, lng=172.61110648037663
13:20:18 - warn: Unhandled object in map update: FQuestUpdate
13:20:18 - debug: Use building b8753a8e-b460-11e7-a456-0d818eb6f954
13:20:28 - debug: Map Refresh lat=-43.52284870673067, lng=172.61114008175417
13:20:28 - warn: Unhandled object in map update: FQuestUpdate
13:20:28 - debug: Use building b8753a8e-b460-11e7-a456-0d818eb6f954

**Comment by niicojs** [comment]
That's because you have a quest active or something like that? Or maybe a quest nearby?
I've never work with quests so it's not implemented.

**Comment by mitviet1** [comment]
could be... but it seems that warning is now gone after I stopped the
dracobot and logged on phone to collect coins.  And now, all is well when I
am back running the bot.  I guessed you can close the issue and I will try
to see if I can duplicate the issue again tomorrow by initiating another
Quest.  Thanks for getting back so quick.  I'll let you know either way.

**Comment by mitviet1** [comment]
it appeared new Draco api is now active.  I ran an update and seemed to get an error and thus could not run dracobot to test this.  Here's the error msg. 
C:\Users\......\dracowalker>npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for draconode@^0.4.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'dracowalker'
npm ERR! notarget

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\......\AppData\Roaming\npm-cache\_logs\2018-02-16T02_06_02_505Z-debug.log

C:\Users\......\dracowalker>tsc

C:\Users\......\dracowalker>node ./bin/app.js
21:06:23 - debug: Using config file config.yaml.
21:06:23 - info: App starting...
21:06:23 - info: go to http://ui.dracoapi.ml/ for ui
21:06:23 - debug: Socket server listening at 8000
21:06:23 - debug: Init walker...
21:06:23 - debug: Ping server...
21:06:23 - error:  Error: Error from server: 409 - Conflict
    at Client.call (C:\Users\......\dracowalker\node_modules\draconode\bin\index.js:141:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
21:06:23 - error: Exiting.

**Comment by niicojs** [comment]
sorry, forgot to push a button.
try again
