### ISSUE TITLE
new update?

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#25]
the bot was workin few days ago and now get get the same issue again.

error: Error: Error from server: 409 - Conflict
at Client.call (C:\Users......\dracowalker\node_modules\draconode\bin\index.js:141:19)

**Comment by niicojs** [comment]
are you up to date?

**Comment by Nackenschelle** [comment]
yes i use the altest build

**Comment by niicojs** [comment]
could you check again?
are you running it from source or binary build?

**Comment by Nackenschelle** [comment]
ok the latest build is working
thanks dude
