### ISSUE TITLE
Error on startup after latest Update

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#27]
14:29:23 - info: Start hatching a 5km egg.

(node:27656) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error from server: 412 - Precondition Failed

(node:27656) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

-----------------------------------------------------------

And alsothis: 

14:33:23 - error:  Error: Error from server: 412 - Precondition Failed
    at Client.call (F:\snapshot\dracowalker\node_modules\draconode\bin\index.js:141:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
14:33:23 - error:  __type=FServiceError, args=[], cause=EGG_NOT_FOR_INCUBATOR

**Comment by niicojs** [comment]
could you send me your state.json file on discord?

**Comment by Nackenschelle** [comment]
yes one moment

**Comment by Nackenschelle** [comment]
is the discord linked anywhere here :'D
cannot fin them :P

**Comment by niicojs** [comment]
https://discord.gg/8vkzZ2r

**Comment by mitviet1** [comment]
For me today I have seen the same 'error' with the Hatching egg process.  The bot however continues to work as normal and only show this error when hatching eggs.

**Comment by Nackenschelle** [comment]
Latest Build is fixing the issue.
#Closerequest

**Comment by niicojs** [comment]
if @mitviet1 you can also test: https://ci.appveyor.com/project/niicojs/dracowalker/build/artifacts

**Comment by mitviet1** [comment]
it looks like the Quest updates is fine now.  But today I start seeing
warning messages relating to Egg hatching...

13:39:59 - debug:   12 Glim candies.
13:39:59 - info: Egg hatched, received a Kobold
13:40:08 - debug: Map Refresh lat=-43.51945550726218, lng=172.61995271713693
13:40:09 - warn: Unhandled object in map update: FQuestUpdate
13:40:19 - debug: Map Refresh lat=-43.51928240336522, lng=172.6198222319478
13:40:19 - warn: Unhandled object in map update: FQuestUpdate
13:40:29 - debug: Map Refresh lat=-43.51910377437595, lng=172.6196845705552
13:40:29 - warn: Unhandled object in map update: FQuestUpdate
13:40:39 - debug: Map Refresh lat=-43.51893315835792, lng=172.6195888025996
13:40:39 - warn: Unhandled object in map update: FQuestUpdate
13:40:40 - debug: Dispatch incubators
13:40:40 - info: Start hatching a 5km egg.
13:40:49 - debug: Map Refresh lat=-43.51882609120582, lng=172.6198213064698
13:40:58 - warn: Unhandled object in map update: FQuestUpdate
13:40:58 - debug: Use building f3366e5f-b430-11e7-b961-6fbd1e4c451d

**Comment by niicojs** [comment]
don't you mean the other way around?

**Comment by mitviet1** [comment]
You are right...  You know like living in the US where we put first name
first and last name last and the rest of the world is the other way
around.  LOL.

**Comment by mitviet1** [comment]
I will try to complete the Quest soon and let you know.  Don't think
there's anything you need to do.  Thanks again.

**Comment by niicojs** [comment]
If someone can send me an account with this warning I'll sort it out

**Comment by mitviet1** [comment]
Hi, a favor please.  Can you NOT popup the confirmation Y/N each time we
want to transfer a creature?  This is very tiresome when we want to mass
transfer a bunch of low CPs mons.  Thanks.

**Comment by niicojs** [comment]
click settings you can deactivate that
