### ISSUE TITLE
Error when starting to hatch an egg and strange warning

### ISSUE THREAD

**Issue by xandymp** [dracoapi/dracowalker#29]
Hi there i'm using the bot for 3 days now and i'm loving it, I was always getting this warn message but it was working with no problem.

```
warn: Unhandled object in map update: FMentorshipAwardUpdate
```
But today this error was shown when the bot started
```
info: Start hatching a 5km egg.
(node:11436) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error from server: 412 - Precondition Failed
(node:11436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
and then it showed this error again like this.
```
info: Start hatching a 5km egg.
error:  Error: Error from server: 412 - Precondition Failed
    at Client.call (C:\snapshot\dracowalker\node_modules\draconode\bin\index.js:141:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error:  __type=FServiceError, args=[], cause=EGG_NOT_FOR_INCUBATOR
```

**Comment by niicojs** [comment]
I'm guessing you install binary from releases.
Could you try using one from here: https://ci.appveyor.com/project/niicojs/dracowalker/build/artifacts?

**Comment by xandymp** [comment]
Yes I used it from the releases. The error message disapeared, but the warning is still there I think it's because I have some map fragments for the golden egg hunt.

**Comment by niicojs** [comment]
Ok, egg related message disappeared right? I'll push it to release soon.

the remaining warning is about FMentorshipAwardUpdate? Didn't implement that.

**Comment by xandymp** [comment]
Yes the egg error message disappeared. The other warning is 
`
warn: Unhandled object in map update: FMentorshipAwardUpdate
`
It just keep flooding the messages, but the bot still works with no problems.

**Comment by xandymp** [comment]
And now it started showing this other message
`warn: Unhandled object in map update: FIngameNotifications`
But no problem just letting you know about the warnings. Since there is no problem you can close this if you want to.

**Comment by niicojs** [comment]
@xandymp I handled `FIngameNotifications` in latest dev build if you want to test (I never encountered this one...)

**Comment by xandymp** [comment]
Sure, I'll give it a try, don't know how or why but the warning just vanished after some time. I think it was because of the notification about dracoins. I will wait some time and see if the warning shows up again.
I just need some instructions about how you want me to do the tests. Do I need to download something? Is there a link to these dev build?

**Comment by niicojs** [comment]
dev buils are here: https://ci.appveyor.com/project/niicojs/dracowalker/build/artifacts

**Comment by xandymp** [comment]
Ok, there isn't anything there yet right? When I click on the link the artifact page is empty. I'll check it again later.

**Comment by niicojs** [comment]
Yes, apparently last build failed. It should be better now.

**Comment by xandymp** [comment]
Ok, I just need to download the .exe and use the bot like before right?
Do I need to update anything else?

**Comment by niicojs** [comment]
just the exe
