### ISSUE TITLE
Turn Dracowalk into a map ? possible?

### ISSUE THREAD

**Issue by nocomp** [dracoapi/dracowalker#35]
hi,
is it possible to turn dracowalk into a map displaying where creatures are? is it possible?
thxx for helping

**Comment by niicojs** [comment]
that's not currently how it works. feel free to PR.

**Comment by nocomp** [comment]
PR = ?

**Comment by niicojs** [comment]
Pull Request - modification of the app

**Comment by nocomp** [comment]
ok , i ve added one, hope i ve did it the right way
thxx a lot

**Comment by niicojs** [comment]
What I mean is, do the modification yourself and I'll add it to the project.
