### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#38]
Hey i found a new error after starting the bot today

debug: Try catching a wild Potty
deprecated, please use client.creatures.encounter
deprecated, please use client.creatures.catch

everything is working fine but is spams on every interaction
stop spin, catch, treasure and co

**Comment by niicojs** [comment]
Which version do you use?
Could you check with latest from https://ci.appveyor.com/project/niicojs/dracowalker/build/artifacts?

**Comment by Nackenschelle** [comment]
ok this one fixed the issue thanks alot
