### ISSUE TITLE
all stopped "api required" watermark displayed

### ISSUE THREAD

**Issue by nocomp** [dracoapi/dracowalker#39]
hi,
bit is not working anymore no stop, dolmen, arena are showing, and i have a grey "api required"' watermark all over the map.
config file was working fine yesterday

**Comment by niicojs** [comment]
I've just published a new version of the ui, maybe you reload it at the wrong time.
Could you update the bot to latest version (stable or dev, as you want), reload the ui?
If you still have an issue, please post a screenshot

**Comment by nocomp** [comment]
i get network error when i try to download here
https://ci.appveyor.com/project/niicojs/dracowalker/build/artifacts

**Comment by niicojs** [comment]
You are using OpenCycleMap right? 
Try to use another one, like OpenStreetMap.

**Comment by nocomp** [comment]
all ok with openstreet map .
thxx a lot!
