### ISSUE TITLE
EGG_NOT_FOR_INCUBATOR

### ISSUE THREAD

**Issue by nocomp** [dracoapi/dracowalker#41]
hi,
on linux version i am having this error showing up:

00:30:42 - info: Start hatching a 2km egg.
00:30:42 - error:  Error: Error from server: 412 - Precondition Failed
    at Client.call (/snapshot/dracowalker/node_modules/draconode/bin/index.js:141:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
00:30:42 - error:  __type=FServiceError, args=[], cause=EGG_NOT_FOR_INCUBATOR
^C

hope it helps

thxx for the great work

**Comment by nocomp** [comment]
hmmm, no eggs in incubator
https://imgur.com/a/Nn8x9

bug?

**Comment by niicojs** [comment]
is this with latest version?

**Comment by nocomp** [comment]
i think so but not quite sure
i ve enable one by hand and since it s all ok,
weird
i keep you posted if new issues.
thx for your time

**Comment by niicojs** [comment]
next time, I'll need the state.json file just after you got the error

**Comment by nocomp** [comment]
oki will do

**Comment by nocomp** [comment]
where is the file state.jsn? can t find it

**Comment by niicojs** [comment]
in the data folder

**Comment by nocomp** [comment]
here we go
https://pastebin.com/aVvgpbCi

**Comment by niicojs** [comment]
(thanks, I deleted it cause it may contain some info you don't want to be public)

**Comment by nocomp** [comment]
thxx a lot, i thought i d cleaned what was needed :)

**Comment by niicojs** [comment]
could you tell me if this is still happening?

**Comment by nocomp** [comment]
hi,
sorry i couldn t reply before.
so fat so good regarding this bug, no idea why... but instead i have one error coming often, and it was here before the update they just pushed, here it is:
19:31:53 - warn: Unhandled object in map update: FQuestUpdate
19:32:04 - error:  Error: Error from server: 412 - Precondition Failed
    at Client.call (C:\snapshot\dracowalker\node_modules\draconode\bin\index.js:143:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
19:32:04 - error:  __type=FServiceError, args=[], cause=SESSION_GONE
PS D:\docs\dracowalker>


i really neeed to get this proxy thing working in order to help you more, i ll try this evening

**Comment by niicojs** [comment]
could you create another issue for this?

**Comment by nocomp** [comment]
done,
i tried to install the proxy stuff, install gave error, for version 8 or 9, need to find an alternative
