### ISSUE TITLE
[♥Questions]

### ISSUE THREAD

**Issue by nocomp** [dracoapi/dracowalker#42]
hi
i ve logged my bot account for use the spades for golden egg hunt.
one thing i ve noticed, no artifacts present, and on the map i never see the treasure box, ix there anything to add in config file in order to get that used?
also is there something to add in config file in order to force to enter in portal?
thxx for yoru time

**Comment by niicojs** [comment]
Chests are found and opened (or they should). I may not add them into the map, I'll check.
The bot should enter mother of dragons and start incubation also.
I don't play the game, so I haven't implemented other stuffs

**Comment by nocomp** [comment]
i don t think that items found in boxes are added, cause all my bot account show zero artefact, simply not possible.
also i don t think that bot goes in the rift, no arcana type creature are caught.
this is all the feedback i can give you so far :)

**Comment by niicojs** [comment]
try using `human` router.
Something like:
```
router: 
  name: human
  prioritizechest: true
  followroads: false
```

**Comment by nocomp** [comment]
ok, i try now
where can we find all options possible to use?

**Comment by niicojs** [comment]
https://github.com/dracoapi/dracowalker/wiki

**Comment by nocomp** [comment]
thxx a lot

**Comment by nocomp** [comment]
last question,
i ve just noticed that a dragon egg has been used, that means  the bot entered in the portal and found mod.
why it didn t also caught creature in the rift? With the bot we catch no arcana type creature, is there something to add in the config file? i didn t found it
here is the screen shot
https://imgur.com/a/QyAVd

thxx for your time

**Comment by niicojs** [comment]
no idea... 
there is nothing in config to do, maybe in a rift the api calls are different.

**Comment by nocomp** [comment]
oki, well can t help you more on that :)
thxx niicojs

**Comment by niicojs** [comment]
Actually you can.
This will help me:
- install https://github.com/dracoapi/nodedracoproxy
- configure your phone to go through this proxy
- install the certificate if needed
- go in a rift and catch a creature
- send me the data created

**Comment by nocomp** [comment]
ok will do in 2-3h when back home
thxx

**Comment by nocomp** [comment]
hmmm
same kind of error on 2 laptop
nocomp@ubuntu:~/nodedracoproxy$ node ./bin/index.js
/home/nocomp/nodedracoproxy/bin/index.js:9
async function Main() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
nocomp@ubuntu:~/nodedracoproxy$ 


what is weird, on kali, node command dont exist need to use nodejs

if you know another proxysoft that log everything let me know

**Comment by niicojs** [comment]
It's because your node install is too old.
If you use something else I'll probaly manage to import it.

**Comment by nocomp** [comment]
weird, i just installed it today :/

**Comment by niicojs** [comment]
`node -v`?

**Comment by nocomp** [comment]
i ve uninstall and reinstalled

nocomp@ubuntu:~/nodedracoproxy$ nodejs ./bin/index.js 
/home/nocomp/nodedracoproxy/bin/index.js:9
async function Main() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
nocomp@ubuntu:~/nodedracoproxy$ nodejs -v
v4.2.6
nocomp@ubuntu:~/nodedracoproxy$

**Comment by niicojs** [comment]
v4 is very old, as I said current is v9, don't install anything below v8

**Comment by nocomp** [comment]
hmmm how do you install v9 from apt-get  ? special repo?

**Comment by niicojs** [comment]
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
