### ISSUE TITLE
error exceed daily request

### ISSUE THREAD

**Issue by nocomp** [dracoapi/dracowalker#43]
hi,
just got these messages on all my accounts (all they have their own api code)
nocomp@ubuntu:~/dracowalker$ ./draco data/config.yaml 
03:59:52 - info: App starting...
03:59:52 - info: go to http://ui.dracoapi.ml/ for ui
03:59:55 - info: Client started...
03:59:59 - error:  Error: You have exceeded your daily request quota for this API.
    at StopRouter.generateWaypoint (/snapshot/dracowalker/bin/lib/router/BaseRouter.js:28:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
04:00:00 - error:  Error: You have exceeded your daily request quota for this API.
    at StopRouter.generateWaypoint (/snapshot/dracowalker/bin/lib/router/BaseRouter.js:28:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
^C
even if i change human to stops, same error,  on my direction api dashboard, it says 23 request, 21 errors, , any idea what can be wrong?

**Comment by niicojs** [comment]
https://github.com/dracoapi/dracowalker/wiki/Google-Maps

**Comment by nocomp** [comment]
yes i know, even if i change the key i still get the error

**Comment by nocomp** [comment]
i think cause i have a free plan, with 3 bots running, i ve reached the max call, i ll check tomorrow and keep you posted
thx a lot

**Comment by niicojs** [comment]
you can also do `followroads: false` in router which will go straight from target to target without using google directions
