### ISSUE TITLE
buff undefined

### ISSUE THREAD

**Issue by xandymp** [dracoapi/dracowalker#46]
Today I opened a chest and got this warn of buff undefined.
So I opened the app on my phone to take a look about it and it was the 2x more creatures from pheromone buff.

**Comment by xandymp** [comment]
Sorry that was the only thing on the debug info.
`Buff received. undefined.`

**Comment by niicojs** [comment]
ok, found it
should be better now

**Comment by xandymp** [comment]
Should I download a new dev version?

**Comment by niicojs** [comment]
yes
