### ISSUE TITLE
Error bag is full

### ISSUE THREAD

**Issue by xandymp** [dracoapi/dracowalker#48]
The bot was running ok, but then it leveled up to level 25. It received too much items and the bag was full with 321/300 and then it started to get this error message.

`error: Unable to spin`
`error:  Error: Error from server: 412 - Precondition Failed
    at Client.call (C:\snapshot\dracowalker\node_modules\draconode\bin\index.js:148:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`
`error:  __type=FServiceError, args=[], cause=BAG_IS_FULL`

After cleaning the bag manually it started to work with no problem.

**Comment by niicojs** [comment]
ok, it now wait for the bag to have room again before trying to spin
