### ISSUE TITLE
got following error

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#5]
error TS2468: Cannot find global value 'Promise'.
lib/api.ts(1,25): error TS2307: Cannot find module 'winston'.
lib/api.ts(2,20): error TS2307: Cannot find module 'lodash'.
lib/api.ts(4,28): error TS2307: Cannot find module 'draconode'.
lib/api.ts(56,32): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
lib/api.ts(89,35): error TS2339: Property 'from' does not exist on type 'ArrayConstructor'.
lib/data.ts(1,27): error TS2307: Cannot find module 'nedb-promise'.
lib/data.ts(2,25): error TS2307: Cannot find module 'winston'.
lib/player.ts(1,20): error TS2307: Cannot find module 'lodash'.
lib/player.ts(2,25): error TS2307: Cannot find module 'winston'.
lib/player.ts(3,27): error TS2307: Cannot find module 'bluebird'.
lib/player.ts(4,28): error TS2307: Cannot find module 'draconode'.
lib/player.ts(5,28): error TS2307: Cannot find module 'dracotext'.
lib/player.ts(9,16): error TS2304: Cannot find name 'require'.
lib/player.ts(70,39): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/player.ts(170,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/player.ts(174,34): error TS2339: Property 'find' does not exist on type 'any[]'.
lib/player.ts(191,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/player.ts(203,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/player.ts(232,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/proxy.ts(1,20): error TS2307: Cannot find module 'lodash'.
lib/proxy.ts(2,25): error TS2307: Cannot find module 'winston'.
lib/proxy.ts(3,25): error TS2307: Cannot find module 'moment'.
lib/proxy.ts(4,26): error TS2307: Cannot find module 'request-promise-native'.
lib/proxy.ts(5,20): error TS2307: Cannot find module 'mz'.
lib/proxy.ts(7,17): error TS2304: Cannot find name 'require'.
lib/proxy.ts(35,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/proxy.ts(53,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/proxy.ts(93,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/router/BaseRouter.ts(1,23): error TS2304: Cannot find name 'require'.
lib/router/BaseRouter.ts(2,16): error TS2304: Cannot find name 'require'.
lib/router/BaseRouter.ts(10,16): error TS2339: Property 'assign' does not exist on type 'ObjectConstructor'.
lib/router/CreatureRouter.ts(1,20): error TS2307: Cannot find module 'lodash'.
lib/router/CreatureRouter.ts(2,28): error TS2307: Cannot find module 'draconode'.
lib/router/CreatureRouter.ts(6,24): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/router/CreatureRouter.ts(11,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/router/CreatureRouter.ts(23,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/router/StopRouter.ts(1,20): error TS2307: Cannot find module 'lodash'.
lib/router/StopRouter.ts(2,25): error TS2307: Cannot find module 'winston'.
lib/router/StopRouter.ts(3,28): error TS2307: Cannot find module 'draconode'.
lib/router/StopRouter.ts(7,24): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/router/StopRouter.ts(20,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/router/StopRouter.ts(34,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/walker.ts(1,27): error TS2307: Cannot find module 'bluebird'.
lib/walker.ts(2,25): error TS2307: Cannot find module 'winston'.
lib/walker.ts(8,23): error TS2304: Cannot find name 'require'.
lib/walker.ts(9,16): error TS2304: Cannot find name 'require'.
lib/walker.ts(50,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
lib/walker.ts(117,32): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
ui/socket.server.ts(1,25): error TS2307: Cannot find module 'winston'.
ui/socket.server.ts(2,20): error TS2307: Cannot find module 'lodash'.
ui/socket.server.ts(3,26): error TS2307: Cannot find module 'fastify'.
ui/socket.server.ts(37,19): error TS2304: Cannot find name 'require'.
ui/socket.server.ts(132,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
ui/socket.server.ts(141,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
ui/socket.server.ts(160,11): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
app.ts(1,1): error TS2304: Cannot find name 'require'.
app.ts(3,25): error TS2307: Cannot find module 'winston'.
app.ts(4,28): error TS2307: Cannot find module 'draconode'.
app.ts(5,20): error TS2307: Cannot find module 'lodash'.
app.ts(6,21): error TS2307: Cannot find module 'mz/fs'.
app.ts(7,25): error TS2307: Cannot find module 'moment'.
app.ts(8,27): error TS2307: Cannot find module 'bluebird'.
app.ts(9,28): error TS2307: Cannot find module 'dracotext'.
app.ts(18,16): error TS2304: Cannot find name 'require'.
app.ts(23,5): error TS2304: Cannot find name 'process'.
app.ts(50,16): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
app.ts(110,21): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
app.ts(133,9): error TS2304: Cannot find name 'process'.
app.ts(162,16): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
app.ts(199,30): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
app.ts(222,16): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

**Comment by niicojs** [comment]
is this when compiling with typescript? are you up to date on both node and typescript?

**Comment by Nackenschelle** [comment]
fixed the issue thx alot

**Comment by niicojs** [comment]
you don't seem up to date, it seems you are using an old version of the `draconode` dependencie
