### ISSUE TITLE
Banned after using Bot for 10 Min

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#54]
i used the latest Version for 10 minutes than i got banned

Error Code:
12:46:08 - error:  Error: Error from server: 412 - Precondition Failed
    at Client.call (F:\snapshot\dracowalker\node_modules\draconode\bin\index.js:148:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
12:46:08 - error:  __type=FServiceError, args=[AutoBySuspicion], cause=USER_BANNED

**Comment by xandymp** [comment]
We were discussing about that on
(https://github.com/dracoapi/dracowalker/issues/50)

**Comment by Nackenschelle** [comment]
thx @xandymp
