### ISSUE TITLE
Autorelease don't work every time

### ISSUE THREAD

**Issue by VirtualS031** [dracoapi/dracowalker#60]
![draco1](https://user-images.githubusercontent.com/33521358/37862816-ae220324-2f53-11e8-8320-2fc90b028a74.PNG)
![draco](https://user-images.githubusercontent.com/33521358/37862817-ae3dec1a-2f53-11e8-8d2a-33443a42be40.PNG)
![draco2](https://user-images.githubusercontent.com/33521358/37862818-ae576302-2f53-11e8-8a87-74d00b462290.PNG)

**Comment by niicojs** [comment]
When you set `autorelease = true` is release the caught pokemon only is cp is lower than existing **and** (stamina + attack) is lower than existing.

**Comment by VirtualS031** [comment]
What happened with 100% IV?

**Comment by niicojs** [comment]
I don't get the question

**Comment by VirtualS031** [comment]
Does autoresolve 100% Iv but lower CP?

**Comment by VirtualS031** [comment]
I transfer all potty and after 20 minutes
![draco3](https://user-images.githubusercontent.com/33521358/37864511-6bfbd8d6-2f70-11e8-8e92-508c9d1faca6.PNG)

after 20 minutes

**Comment by VirtualS031** [comment]
You mean if catch stronger don't transfer lower?
Maybe that's it.

Sorry

**Comment by niicojs** [comment]
new dev version handle this a little bit differently if you want to test
