### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#65]
I use the latest update but on login i got this message:
Error: Error from server: 409 - Conflict
how can i fix it?

**Comment by niicojs** [comment]
Could you paste be version printed at startup?

**Comment by Nackenschelle** [comment]
at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
debug: Using config file config.yaml.
info: App starting...
debug: Init walker...
debug: Ping server...
error:  Error: Error from server: 409 - Conflict
    at Client.call (F:\snapshot\dracowalker\node_modules\draconode\bin\index.js:160:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Nackenschelle** [comment]
this is everything i get in the log
i used the latest version

**Comment by niicojs** [comment]
Where did you download it?
There is information missing, you should have the version displayed after "App Starting".
