### ISSUE TITLE
Unhandled object in map update: FUserInfo

### ISSUE THREAD

**Issue by Tinoxy** [dracoapi/dracowalker#66]
### Steps to Reproduce the Problem

  1.
  1.
  1.

### Specifications
  - Version: 1.0.93
  - Platform: windows
### Logs
Paste logs from console here (or file if you don't have console).
20:00:03 - warn: Unhandled object in map update: FUserInfo

**Comment by niicojs** [comment]
thanks for reporting
does not seem to be anything, should be fixed now

**Comment by Tinoxy** [comment]
Thanks i test it out ;) and have you a fan discord for the bot?
