### ISSUE TITLE
can someone tell me how to run it?

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#7]
title

**Comment by niicojs** [comment]
what did you try?
did you run the few commands in README?
If so, create a config.yaml based on the example in data folder and try to run it.

**Comment by Nackenschelle** [comment]
i installed the latest version of node and typescript

i also created the config.yaml in the data folder and fill out my login and location.

i get following errors 
node_modules/draconode/bin/draco/deserializer.d.ts(21,62): error TS2304: Cannot find name 'Set'.
node_modules/draconode/bin/draco/deserializer.d.ts(22,89): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/deserializer.d.ts(23,88): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(82,21): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(83,17): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(146,22): error TS2304: Cannot find name 'Set'.
node_modules/draconode/bin/draco/objects.d.ts(189,14): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(237,18): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(306,20): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(338,19): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(374,12): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(438,17): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(471,12): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(753,14): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(939,16): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(941,12): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(958,16): error TS2304: Cannot find name 'Set'.
node_modules/draconode/bin/draco/objects.d.ts(1015,17): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(1048,25): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(1101,20): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(1181,17): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(1190,12): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/objects.d.ts(1191,20): error TS2304: Cannot find name 'Map'.
node_modules/draconode/bin/draco/serializer.d.ts(23,30): error TS2304: Cannot find name 'Set'.
node_modules/draconode/bin/draco/serializer.d.ts(25,26): error TS2304: Cannot find name 'Map'.
app.ts(11,23): error TS2307: Cannot find module './lib/api'.
app.ts(12,25): error TS2307: Cannot find module './lib/proxy'.
app.ts(13,20): error TS2307: Cannot find module './lib/walker'.
app.ts(14,20): error TS2307: Cannot find module './lib/player'.
app.ts(15,26): error TS2307: Cannot find module './ui/socket.server'.
app.ts(50,16): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
app.ts(100,26): error TS2339: Property 'acceptLicence' does not exist on type 'Client'.
app.ts(110,21): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
app.ts(162,16): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
app.ts(173,43): error TS2339: Property 'evolve' does not exist on type 'Client'.
app.ts(199,30): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
app.ts(222,16): error TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.

**Comment by niicojs** [comment]
Could you send me the result of node -v

**Comment by Nackenschelle** [comment]
shows v9.2.0

**Comment by niicojs** [comment]
and typescript? `tsc -v`

**Comment by Nackenschelle** [comment]
Version 2.6.2

**Comment by Nackenschelle** [comment]
i download the latest version of both

**Comment by niicojs** [comment]
I don't get it. Version are fine but it seems it doesn't get it's new javascript.
Are you running tsc on the root of the project? I.e alongside the tsconfig file?

**Comment by Nackenschelle** [comment]
Yes. Normaly it has to work but i dont find the error.
i also redownlaoded the files.
maybe i do something wrong.
is it possible for you to make a short video how to run the script?

maybe iam not the only person with that kind of problem

**Comment by niicojs** [comment]
It's litterally what's written on the readme.  
https://github.com/dracoapi/dracowalker/wiki/install

**Comment by Nackenschelle** [comment]
thanks i will take a look

**Comment by Nackenschelle** [comment]
ok it works now.
but i get following error 

23:30:13 - info: App starting...
23:30:13 - info: go to http://ui.dracoapi.ml/ for ui
23:30:13 - info: Using proxy: http://localhost:8888
23:30:14 - error: Bad proxy
23:30:14 - error: Exiting.

**Comment by niicojs** [comment]
1. could you tell me what you did wrong before?
2. you have to configure a proxy

**Comment by Nackenschelle** [comment]
1. idk i did the same like in the video
2. proxy works now but it shows BadAuthentication on google but my email and pw are correct

**Comment by niicojs** [comment]
could you paste your config file somewhere? (without the password)

**Comment by Nackenschelle** [comment]
# User credentials
credentials:
  # DEVICE or GOOGLE
  login: GOOGLE
  deviceId: 'aaa-aaa'
  username: 'Dennis.Wegener1990@gmail.com'
  password: 'xxxxxxxx'

# Initial position when starting the app (ex: Paris)
pos:
  lat: 48.8628407
  lng: 2.3286178

# Speed in km/h (default = 4)
# auto = 90% of run speed from server
speed: auto

# If nothing is set, direct call will be made
# If a proxy is set it will be used (like http://server:8080)
# If 'auto' is set, a proxy from https://www.sslproxies.org will be used
proxy: 
  # url: auto
  url: http://87.169.190.80:8080

# true to enable ui, go to ui.dracoapi.ml to see it
ui:
  enabled: true

**Comment by niicojs** [comment]
Don't know, works for me.
There may be something with your account, like multi factor enabled or something.
I'll need a test account that doesn't work to understand what's happening.

**Comment by Nackenschelle** [comment]
it works now
thread can be closed

awesome tool

**Comment by niicojs** [comment]
Ok, good to know.
Would be nice if you can tell me what you did wrong in the first place so it gets added to FAQ.
