### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by MadD0g25** [dracoapi/dracowalker#72]
Good evening,

I have a connection problem with the bot.
When trying to open it, it closes immediately.
Do you know where this problem can come from ?

### Specifications
  - Version: Last version
  - Platform: Windows 10

### Logs
error:  Error: Error from server: 409 - Conflict
    at Client.call (C:\snapshot\dracowalker\node_modules\draconode\bin\index.js:160:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Thank you for your reply !

**Comment by Nackenschelle** [comment]
same here i think there is an game update.
409 - Conflict normaly means there is an api update

pls update dude

**Comment by niicojs** [comment]
Try latest dev version
