### ISSUE TITLE
cant login 

### ISSUE THREAD

**Issue by Nackenschelle** [dracoapi/dracowalker#76]
hey i think there is an game update
can someone confirm this?
pls update

**Comment by niicojs** [comment]
Could you test latest dev ?

**Comment by Nackenschelle** [comment]
ok will test it

**Comment by Nackenschelle** [comment]
ok dont work for me

error
> pkg@4.3.4
> Warning Cannot stat, ENOENT
  C:\Users\Marvin\Desktop\dracowalker-master\version
  The file was required from 'C:\Users\Marvin\Desktop\dracowalker-master\bin\lib\versions.js'

**Comment by niicojs** [comment]
Sorry. Could you check again?

**Comment by bebek-air** [comment]
I do, but i got error message

```
[xx:xx:xx] info - App starting...
(node:6930) ExperimentalWarning: The fs.promises API is experimental
(node:6930) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/snapshot/dracowalker/version'
`(node:6930)` UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6930) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
my box: ubuntu 14.04 64 bit

**Comment by niicojs** [comment]
@bebek-air is it using one of my binaries or with source?

**Comment by niicojs** [comment]
I think I've corrected this issue if you want to try.

**Comment by bebek-air** [comment]
Sorry, i far away a bit, downloading, i will report soon

**Comment by bebek-air** [comment]
Everything is great, thank you

**Comment by Nackenschelle** [comment]
works fine now thanks alot
